name: ad_service
description: A service for managing Google Mobile Ads in a Flutter app.
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^2.3.0
